# Change these first
owner: Elythera # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: Site Principal
    url: https://www.elythera.com
  - name: Nextcloud
    url: https://nc.elythera.com
  - name: Gitea
    url: https://git.elythera.com
  - name: Pterodactyl
    url: https://pt.elythera.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.elythera.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Elythera Status
  introTitle: "**Bienvenue** sur la page status d'Elythera."
  introMessage: Au cas où, si un incident survient sur nos services, vous en serez alors informés sur cette page
  navbar:
    - title: Accueil
      href: https://elythera.com
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/Vg7egG3RZC

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
